mutation CreateSeedData @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") @transaction {
  user_insertMany(data: [
    {
      id: "550e8400-e29b-41d4-a716-446655440000",
      username: "demouser1",
      email: "demouser1@example.com",
      createdAt: "2024-03-15T12:00:00Z"
    },
    {
      id: "550e8400-e29b-41d4-a716-446655440001",
      username: "demouser2",
      email: "demouser2@example.com",
      createdAt: "2024-03-15T12:00:00Z"
    }
  ])
  comment_insertMany(data: [
    {
      userUid: "550e8400-e29b-41d4-a716-446655440000",
      content: "Example comment from demouser1"
    },
    {
      userUid: "550e8400-e29b-41d4-a716-446655440001",
      content: "Example comment from demouser2"
    }
  ])
}